# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#

# user1 = User.create(email:'test1@test1.com', password: 'password', password_confirmation: 'password')
# user2 = User.create(email:'test2@test2.com', password: 'password', password_confirmation: 'password')
# user3 = User.create(email:'test3@test3.com', password: 'password', password_confirmation: 'password')
# user4 = User.create(email:'test4@test4.com', password: 'password', password_confirmation: 'password')
# user5 = User.create(email:'test5@test5.com', password: 'password', password_confirmation: 'password')
# user1.posts.create(title:'post1', body:'this is body1')
# user1.posts.create(title:'post2', body:'this is body2')
# user1.posts.create(title:'post3', body:'this is body3')
# user1.posts.create(title:'post4', body:'this is body4')
# user2.posts.create(title:'post1', body:'this is body1')
# user2.posts.create(title:'post2', body:'this is body2')
# user2.posts.create(title:'post3', body:'this is body3')
# user2.posts.create(title:'post4', body:'this is body4')
# user3.posts.create(title:'post1', body:'this is body1')
# user3.posts.create(title:'post2', body:'this is body2')
# user3.posts.create(title:'post3', body:'this is body3')
# user3.posts.create(title:'post4', body:'this is body4')
# user4.posts.create(title:'post1', body:'this is body1')
# user4.posts.create(title:'post2', body:'this is body2')
# user4.posts.create(title:'post3', body:'this is body3')
# user4.posts.create(title:'post4', body:'this is body4')
# user5.posts.create(title:'post1', body:'this is body1')
# user5.posts.create(title:'post2', body:'this is body2')
# user5.posts.create(title:'post3', body:'this is body3')
# user5.posts.create(title:'post4', body:'this is body4')